--include("autorun/weapondata.lua")

-- Lua generated by DermaDesigner


Changed = {}
ConWeapon = {}

function WeaponSelectorDerma()

ApplyWeapon(false)

--print("Your name is ".. LocalPlayer():Nick())

--[[
for i = 1, 5 do
	print("Weapon "..i..":" .. LocalPlayer():GetNWString("Wep"..i) )
	print("Table "..i..":" .. table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i)))
end
--]]

local MenuBase = vgui.Create("DFrame")
MenuBase:SetSize(ScrW(),ScrH())
MenuBase:SetPos(0,0)
MenuBase:SetTitle("Weapon Selection")
MenuBase:SetDeleteOnClose(false)
MenuBase:SetDraggable( false )
MenuBase:SetBackgroundBlur(false)
MenuBase:SetVisible( true )
MenuBase.Paint = function()
	draw.RoundedBox( 8, 0, 0, MenuBase:GetWide(), MenuBase:GetTall(), Color( 0, 0, 0, 150 ) )
end
MenuBase:MakePopup()


local MenuBar = vgui.Create( "DMenuBar")
MenuBar:SetParent(MenuBase)
MenuBar:DockMargin( -3,-6,-3,0 ) --corrects MenuBar pos

local M1 = MenuBar:AddMenu( "File" )
M1:AddOption( "Save", function() ApplyWeapon(true) end ):SetIcon( "icon16/page_white_go.png" )
M1:AddOption( "Exit", function() MenuBase:Close() end ):SetIcon( "icon16/folder_go.png" )

local M2 = MenuBar:AddMenu( "Help" )
M2:AddOption( "Filler", function() end )

Icon = {}
Choice = {}
SpawnWeapon = {}


for i=1, 5 do

--http://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index411a-2.html
--table.KeyFromValue( Table table, Var value )

Changed[i] = false

Icon[i] = vgui.Create("ContentIcon")
Icon[i]:SetParent(MenuBase)
Icon[i]:SetPos(i*125 - 125,50)


if LocalPlayer():GetNWString("Wep"..i) == "nil" then 
	Icon[i]:SetName("None")
	Icon[i]:SetMaterial("weapons/swep")
else
	--print(LocalPlayer():GetNWString("Wep"..i))
	Icon[i]:SetName(TableName[i][table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i))])
	if not Material("vgui/entities/".. TableEnt[i][table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i))] .. ".png"):IsError() then
		Icon[i]:SetMaterial("vgui/entities/".. TableEnt[i][table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i))]..".png") 
	else 
		Icon[i]:SetMaterial("weapons/swep")
	end
end


Icon[i].DoClick = function()
	
	
	--print(table.Count(TableEnt[i]))
	local x,y = MenuBase:GetPos()
	Choice[i] = DermaMenu()
		Choice[i]:SetPos(gui.MouseX() - x ,gui.MouseY() - y)
		Choice[i]:SetParent(MenuBase)
		Choice[i]:AddOption("Select A weapon", function() print("Are you fucking serious") end)
		Choice[i]:AddSpacer()
		Choice[i]:SetDrawOnTop(true)
		
	for k=0, table.Count(TableEnt[i]) do
		if TableName[i][k] == nil then return end
		Choice[i]:AddOption(TableName[i][k], function()
		Icon[i]:SetName(TableName[i][k])
		Changed[i] = true
		--print(TableName[i][k])


		
		if not Material("vgui/entities/".. TableEnt[i][k] or "error" .. ".png"):IsError() then
			Icon[i]:SetMaterial("vgui/entities/".. TableEnt[i][k] or "error"..".png") 
		else 
			Icon[i]:SetMaterial("weapons/swep") 
		end
		
		
		
		SpawnWeapon[i] = TableEnt[i][k]	or "nil"
		end):SetIcon( "icon16/gun.png" )

		
	end
	
end


end

end

concommand.Add("selectweapon", WeaponSelectorDerma)


function ApplyWeapon(kdude)

	if kdude == nil or kdude == false then return end

	for i=1, 5 do 
		if Changed[i] == true then
			ConWeapon[i] = SpawnWeapon[i]
		else
			ConWeapon[i] = LocalPlayer():GetNWString("Wep"..i)
		end
	end
	--print("yeah run dude")
	LocalPlayer():EmitSound("buttons/weapon_confirm.wav",100,100)
	RunConsoleCommand("weapon_take",ConWeapon[1],ConWeapon[2],ConWeapon[3],ConWeapon[4],ConWeapon[5])

end
