--include("autorun/weapondata.lua")

-- Lua generated by DermaDesigner

CreateClientConVar("cl_ws_enablecamera", 1, true, true )
CreateClientConVar("cl_ws_enablephysgun", 1, true, true )
CreateClientConVar("cl_ws_enabletoolgun", 1, true, true )
CreateClientConVar("cl_ws_enablemedkit", 1, true, true )
CreateClientConVar("cl_ws_enablenade", 1, true, true )

Changed = {}
ConWeapon = {}

function WeaponSelectorDerma()

ApplyWeapon(false)

--print("Your name is ".. LocalPlayer():Nick())

--[[
for i = 1, 5 do
	print("Weapon "..i..":" .. LocalPlayer():GetNWString("Wep"..i) )
	print("Table "..i..":" .. table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i)))
end
--]]
local MenuBase = vgui.Create("DFrame")
MenuBase:SetSize(125*6 + 250 ,125+55 + 250)
MenuBase:SetPos(0,0)
MenuBase:SetTitle("Weapon Selection")
MenuBase:Center(true)
MenuBase:SetDeleteOnClose(false)
MenuBase:SetDraggable( false )
MenuBase:SetBackgroundBlur(false)
MenuBase:SetVisible( true )
MenuBase.Paint = function()
	draw.RoundedBox( 8, 0, 0, MenuBase:GetWide(), MenuBase:GetTall(), Color( 0, 0, 0, 150 ) )
end
MenuBase:MakePopup()




local MenuBar = vgui.Create( "DMenuBar")
MenuBar:SetParent(MenuBase)
MenuBar:DockMargin( -3,-6,-3,0 ) --corrects MenuBar pos

local M1 = MenuBar:AddMenu( "File" )
M1:AddOption( "Save", function() ApplyWeapon(true) end ):SetIcon( "icon16/page_white_go.png" )
M1:AddOption( "Exit", function() MenuBase:Close() end ):SetIcon( "icon16/folder_go.png" )

local M2 = MenuBar:AddMenu( "Help" )
M2:AddOption( "Filler", function() end )

local Checkbox1 = vgui.Create("DCheckBoxLabel")
Checkbox1:SetParent(MenuBase)
Checkbox1:SetPos( 125*5 + 10,50 + 5 )
Checkbox1:SetText( "Physgun" )
Checkbox1:SetConVar( "cl_ws_enablephysgun" )
Checkbox1:SizeToContents()

local Checkbox2 = vgui.Create("DCheckBoxLabel")
Checkbox2:SetParent(MenuBase)
Checkbox2:SetPos( 125*5 + 10,75 + 5 )
Checkbox2:SetText( "Toolgun" )
Checkbox2:SetConVar( "cl_ws_enabletoolgun" )
Checkbox2:SizeToContents()

local Checkbox3 = vgui.Create("DCheckBoxLabel")
Checkbox3:SetParent(MenuBase)
Checkbox3:SetPos( 125*5 + 10,100 + 5 )
Checkbox3:SetText( "Camera" )
Checkbox3:SetConVar( "cl_ws_enablecamera" )
Checkbox3:SizeToContents()

local Checkbox4 = vgui.Create("DCheckBoxLabel")
Checkbox4:SetParent(MenuBase)
Checkbox4:SetPos( 125*5 + 10,125 + 5 )
Checkbox4:SetText( "Medkit" )
Checkbox4:SetConVar( "cl_ws_enablemedkit" )
Checkbox4:SizeToContents()

local Checkbox5 = vgui.Create("DCheckBoxLabel")
Checkbox5:SetParent(MenuBase)
Checkbox5:SetPos( 125*5 + 10,150 + 5 )
Checkbox5:SetText( "Grenade" )
Checkbox5:SetConVar( "cl_ws_enablenade" )
Checkbox5:SizeToContents()



Icon = {}
Choice = {}
SpawnWeapon = {}


for i=1, 5 do

--http://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index411a-2.html
--table.KeyFromValue( Table table, Var value )

Changed[i] = false

Icon[i] = vgui.Create("ContentIcon")
Icon[i]:SetParent(MenuBase)
Icon[i]:SetPos(i*125 - 125,50)


if LocalPlayer():GetNWString("Wep"..i) == "nil" then 
	Icon[i]:SetName("None")
	Icon[i]:SetMaterial("weapons/swep")
else
	--print(LocalPlayer():GetNWString("Wep"..i))
	--print(TableName[i])
	--print(TableName[1][table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i))])
	Icon[i]:SetName(TableName[i][table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i))])
	if not Material("vgui/entities/".. TableEnt[i][table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i))] .. ".png"):IsError() then
		Icon[i]:SetMaterial("vgui/entities/".. TableEnt[i][table.KeyFromValue(TableEnt[i],LocalPlayer():GetNWString("Wep"..i))]..".png") 
	else 
		Icon[i]:SetMaterial("weapons/swep")
	end
end


Icon[i].DoClick = function()
	
	
	--print(table.Count(TableEnt[i]))
	local x,y = MenuBase:GetPos()
	Choice[i] = DermaMenu()
		Choice[i]:SetPos(gui.MouseX() - x,gui.MouseY() - y)
		Choice[i]:SetParent(MenuBase)
		Choice[i]:MoveToFront()
		Choice[i]:AddOption("Select A weapon", function() print("Are you fucking serious") end)
		Choice[i]:AddSpacer()
		Choice[i]:SetDrawOnTop(true)
		
	for k=0, table.Count(TableEnt[i]) do
		if TableName[i][k] == nil then return end
		Choice[i]:AddOption(TableName[i][k], function()
		Icon[i]:SetName(TableName[i][k])
		Changed[i] = true
		--print(TableName[i][k])


		
		if not Material("vgui/entities/".. TableEnt[i][k] or "error" .. ".png"):IsError() then
			Icon[i]:SetMaterial("vgui/entities/".. TableEnt[i][k] or "error"..".png") 
		else 
			Icon[i]:SetMaterial("weapons/swep") 
		end
		
		
		
		SpawnWeapon[i] = TableEnt[i][k]	or "nil"
		end):SetIcon( "icon16/gun.png" )

		
	end
	
end


end

end

concommand.Add("selectweapon", WeaponSelectorDerma)


function ApplyWeapon(kdude)

	if kdude == nil or kdude == false then return end

	for i=1, 5 do 
		if Changed[i] == true then
			ConWeapon[i] = SpawnWeapon[i]
		else
			ConWeapon[i] = LocalPlayer():GetNWString("Wep"..i)
		end
	end
	--print("yeah run dude")
	LocalPlayer():EmitSound("buttons/weapon_confirm.wav",100,100)
	RunConsoleCommand("weapon_take",ConWeapon[1],ConWeapon[2],ConWeapon[3],ConWeapon[4],ConWeapon[5])

end
